
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

input {
    repeat_delay = 300
    touchpad {
        scroll_factor = 0.6
    }
}

gestures {
    workspace_swipe = true
}

# Laptop lid switch events
exec = ~/.config/hypr/scripts/laptop_lid.sh
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, auto"
