version = 3
final_space = true

# Catppuccin Mocha
[palette]
blue = '#89B4FA'
teal = '#94e2d5'
green = '#A6E3A1'
red = '#F38BA8'
peach = '#F5A97F'
lavendar = '#B4BEFE'
mauve = '#CBA6F7'
pink = '#F5C2E7'
os = '#ACB0BE'
black = '#000000'

# Prompt - First Line
# OS - User - [@Host if SHH] - Path - Python Env - Git
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = '󰒸 '
foreground = 'p:black'
background = 'p:teal'

[[blocks.segments]]
type = 'session'
style = 'powerline'
powerline_symbol = ''
template = ' {{ .UserName }}{{ if .SSHSession }}@{{ index (splitList "." .HostName) 0 }}{{ end }} '
foreground = 'p:black'
background = 'p:blue'

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
template = ' {{ .Path }} '
foreground = 'p:black'
background = 'p:pink'

[blocks.segments.properties]
folder_icon = '....'
home_icon = '~'
style = 'agnoster_short'
max_depth = 3

[[blocks.segments]]
type = 'python'
style = 'powerline'
powerline_symbol = ''
template = """\
    {{ if .Error }} {{ .Error }} {{ else }}\
    {{ if .Venv }} ({{ .Venv }}) {{ end }}\
     {{ .Major }}.{{ .Minor }} \
    {{ end }}\
    """
foreground = 'p:black'
background = 'p:lavendar'

[[blocks.segments]]
type = 'git'
style = 'powerline'
template = """ \
    {{ .HEAD }}\
    {{if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
    {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
    {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
    """
foreground = 'p:black'
background = 'p:mauve'
powerline_symbol = ''

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = true
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

# Right Prompt
# Execution Time
[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "p:os"
template = " ({{ .FormattedMs }}) "

[blocks.segments.properties]
threshold = 500
style = "austin"
always_enabled = true

[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = '{{ .Icon }} '
foreground = 'p:black'
background_templates = [
    '{{ if eq .OS "ubuntu" }}p:peach{{ end }}'
]

# Prompt - Second Line
# 
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
template = ' 󱞩'
foreground = 'p:green'

# Transient Prompt
# 
[transient_prompt]
template = ' 󱞫 '
foreground = 'p:mauve'
