version = 3
final_space = true


# Catppuccin Mocha
[palette]
blue = '#89B4FA'
teal = '#94e2d5'
green = '#A6E3A1'
red = '#F38BA8'
peach = '#F5A97F'
lavendar = '#B4BEFE'
mauve = '#CBA6F7'
pink = '#F5C2E7'
os = '#ACB0BE'


# Prompt - 'Zero-th' Line
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = false

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "p:os"
template = "󱞽 {{ .FormattedMs }}\n"

[blocks.segments.properties]
threshold = 500
style = "austin"
always_enabled = true


# Prompt - First Line
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'session'
style = 'plain'
template = '{{ .UserName }}{{ if .SSHSession }}@{{ index (splitList "." .HostName) 0 }}{{ end }} '
foreground = 'p:teal'

[[blocks.segments]]
type = 'path'
style = 'plain'
template = '{{ .Path }} '
foreground = 'p:pink'

[blocks.segments.properties]
folder_icon = '....'
home_icon = '~'
style = 'agnoster_short'
max_depth = 3

[[blocks.segments]]
type = 'python'
style = 'plain'
template = """\
    {{ if .Error }}{{ .Error }} {{ else }}\
    {{ if .Venv }}({{ .Venv }}) {{ end }}\
     {{ .Major }}.{{ .Minor }} \
    {{ end }}\
    """
foreground = 'p:lavendar'

[[blocks.segments]]
type = 'git'
style = 'plain'
template = """\
    {{ .HEAD }}\
    {{if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
    {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
    {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
    """
foreground = 'p:mauve'

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = true
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '


# Right Prompt
[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'os'
style = 'plain'
template = '{{ .Icon }} '
foreground = 'p:os'
foreground_templates = [
    '{{ if eq .OS "ubuntu" }}p:peach{{ end }}'
]


# Prompt - Second Line
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
template = '󱞩'
foreground = 'p:green'


# Transient Prompt
[transient_prompt]
template = "<p:os>󱞽 {{ .Segments.Executiontime.FormattedMs }}</>\n\n󱞫 "
foreground = 'p:mauve'
